batch_size: 32
seq_len: 720
predict_len: 96
do_eval: True
epoch: 2

dataset: 
  name: TSDataset
  dataset_root: /data/
  train_path: /data/train.csv
  val_path: /data/val.csv
  time_feat: True
  use_holiday: True
  scale: True

info_params:
  freq: 1h
  target_cols: "OT"
  time_col: date


model: 
  name: TiDE
  model_cfg:
    c_in: 1
    num_encoder_layers: 2
    use_revin: False
    drop_prob: 0.5
    hidden_size: 1024
    decoder_output_dim: 8
    temporal_decoder_hidden: 64
    optimizer_params:
      learning_rate: 0.00099
      gamma: 0.5
    patience: 10


  
