Global:
  model: whisper-medium
  mode: predict # check_dataset/train/evaluate/predict
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null


Predict:
  batch_size: 1
  model_dir: "whisper-medium"
  input: "./zh.wav"
  kernel_option:
    run_mode: paddle
