Global:
  model: PicoDet-XS
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/det/det_coco_examples"
  device: gpu:4
  output: "output"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 80
  epochs_iters: 50
  batch_size: 1
  learning_rate: #0.08
  pretrain_weight_path: null
  warmup_steps: #100
  resume_path: null
  log_interval: 10
  eval_interval: 1

Evaluate:
  weight_path: "output/best_model.pdparams"
  log_interval: 10

Predict:
  model_dir: "output/best_model"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_object_detection_002.png"
  kernel_option:
    run_mode: paddle
    batch_size: 1