Global:
  model: AutoEncoder_ad
  mode: train  # check_dataset/train/evaluate/predict
  dataset_dir: "/ssd2/sunting/1230/PaddleTS/ts_anomaly_examples/"
  device: gpu:0
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  time_col: timestamp
  feature_cols: feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24
  label_col: label
  freq: 1
  input_len: 100
  epochs_iters: 1
  batch_size: 128
  learning_rate: 0.001
  log_interval: 10

Evaluate:
  weight_path: "output/best_model/model.pdparams"

Export:
  weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/AutoEncoder_ad.pdparams.tar

Predict:
  batch_size: 1
  model_dir: "output/inference"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/ts/demo_ts/ts_ad.csv"
