Global:
  model: BEVFusion
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/3d/nuscenes"
  device: gpu:0,1,2,3,4,5,6,7
  output: "output"
  load_cam_from: /paddle/model/paddlex/3d/camera.pdparams
  load_lidar_from: /paddle/model/paddlex/3d/lidar.pdparams

CheckDataset:
  convert:
    enable: False
  split:
    enable: False

Train:
  epochs: 2
  batch_size: 2
  learning_rate: 0.001
  warmup_steps: 150

Evaluate:
  batch_size: 1
  weight_path: /paddle/model/paddlex/3d/fusion.pdparams


Export:
  weight_path: /paddle/model/paddlex/3d/fusion.pdparams

# Predict:
#   model_dir: /paddle/model/paddlex/3d/fusion


Predict:
  batch_size: 1
  model_dir: "output/bevfusion"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/face_detection.png"
  kernel_option:
    run_mode: paddle


