Global:
  pipeline_name: anomaly_detection
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/uad_grid.png
  
######################################## Setting ########################################
# Please select the model from bellow `Support`

Pipeline:
  model: STFPM
  batch_size: 1
  device: "gpu"
