Global:
  pipeline_name: image_classification
  input: xxx.jpg
  
######################################## Setting ########################################
# Please select the model from bellow `Support`

Pipeline:
  model: PP-LCNet_x0_5
  batch_size: 1
  device: "gpu"
  # enable_hpi: False

######################################## Support ########################################
NOTE:
  model:
    - PP-LCNet_x0_5
    - PP-LCNet_x0_5
    - PP-LCNet_x0_5
