Global:
  pipeline_name: object_detection
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_object_detection_002.png
  
######################################## Setting ########################################
# Please select the model from bellow `Support`

Pipeline:
  model: PicoDet-S
  batch_size: 1
  device: "gpu"
  # enable_hpi: False

######################################## Support ########################################
NOTE:
  model:
    - PicoDet-S
