Global:
  pipeline_name: OCR
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_001.png
  
Pipeline:
  det_model: PP-OCRv4_mobile_det
  rec_model: PP-OCRv4_mobile_rec
  batch_size: 1
  device: "gpu:0"
