Global:
  pipeline_name: semantic_segmentation
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg
  
######################################## Setting ########################################
# Please select the model from bellow `Support`

Pipeline:
  model: PP-LiteSeg-T
  batch_size: 1
  device: "gpu"

######################################## Support ########################################
NOTE:
  model:
    - PP-LiteSeg-T
