Global:
  pipeline_name: ts_fc
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/ts/demo_ts/ts_fc.csv
  
######################################## Setting ########################################
# Please select the model from bellow `Support`

Pipeline:
  model: DLinear
  batch_size: 1
  device: "gpu:0"
