Global:
  model: whisper-large
  mode: predict # only support predict
  device: gpu:0
  output: "output"

Predict:
  batch_size: 1
  model_dir: "whisper-large"
  input: "https://paddlespeech.bj.bcebos.com/PaddleAudio/zh.wav"
  kernel_option:
    run_mode: paddle
