
pipeline_name: doc_preprocessor
input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/img_rot180_demo.jpg
#input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/doc_test.jpg
use_doc_orientation_classify: True
use_doc_unwarping: True

SubModules:
  DocOrientationClassify:
    module_name: doc_text_orientation
    model_name: PP-LCNet_x1_0_doc_ori
    model_dir: null
    batch_size: 1
  DocUnwarping:
    module_name: image_unwarping
    model_name: UVDoc
    model_dir: null
    batch_size: 1
