pipeline_name: face_recognition

index: None
det_threshold: 0.5
rec_threshold: 0.5
rec_topk: 5

SubModules:
  Detection:
    module_name: object_detection
    model_name: BlazeFace
    model_dir: null
    batch_size: 1 
  Recognition:
    module_name: face_feature
    model_name: MobileFaceNet
    model_dir: null
    batch_size: 1
