
pipeline_name: OCR

##############################################
####### Config for Common OCR
##############################################

input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_001.png
text_type: common

SubModules:
  TextDetection:
    module_name: text_detection
    model_name: PP-OCRv4_mobile_det
    model_dir: null
    batch_size: 1    
  TextRecognition:
    module_name: text_recognition
    model_name: PP-OCRv4_mobile_rec
    model_dir: null
    batch_size: 1

##############################################
####### Config for Seal OCR
##############################################

# input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/seal_text_det.png
# text_type: seal

# SubModules:
#   TextDetection:
#     module_name: text_detection
#     model_name: PP-OCRv4_mobile_seal_det
#     model_dir: null
#     batch_size: 1    
#   TextRecognition:
#     module_name: text_recognition
#     model_name: PP-OCRv4_mobile_rec
#     model_dir: null
#     batch_size: 1
