pipeline_name: PP-ShiTuV2

index: None
score_thres: 0.5
return_k: 5

SubModules:
  Detection:
    module_name: text_detection
    model_name: PP-ShiTuV2_det
    model_dir: null
    batch_size: 1    
  Recognition:
    module_name: text_recognition
    model_name: PP-ShiTuV2_rec
    model_dir: null
    batch_size: 1
